#!/usr/bin/env python3
"""Validate bilingual catalogs and generate immutable Swift tables."""
import argparse
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGET = ROOT / "Sources/PulseCore/LocalizationCatalog.swift"


def generate():
    catalogs = {language: json.loads((ROOT / f"Resources/Localization/{language}.json").read_text())
                for language in ("en", "zh-Hans")}
    if catalogs["en"].keys() != catalogs["zh-Hans"].keys():
        raise ValueError("Locale keys differ")
    specifier = re.compile(r"%(?:@|ld|%)")
    for key, english in catalogs["en"].items():
        chinese = catalogs["zh-Hans"][key]
        if not english or not chinese or specifier.findall(english) != specifier.findall(chinese):
            raise ValueError(f"Empty translation or format mismatch: {key}")
    lines = ["// Generated by scripts/generate_localizations.py; edit Resources/Localization/*.json.",
             "enum LocalizationCatalog {", "    static let strings: [String: [String: String]] = ["]
    for language, messages in catalogs.items():
        lines.append(f'        "{language}": [')
        for key, value in sorted(messages.items()):
            lines.append(f"            {json.dumps(key)}: {json.dumps(value, ensure_ascii=False)},")
        lines.append("        ],")
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != generated:
            parser.exit(1, "Localization tables drifted; run scripts/generate_localizations.py\n")
        print("Localization catalogs and generated tables match")
    else:
        TARGET.write_text(generated)
